# Generated by Django 5.2.6 on 2025-09-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_location_user_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
