# Generated by Django 5.2.6 on 2025-09-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_comment_options_comment_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
