# Generated by Django 5.2.6 on 2025-09-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_privacy_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
    ]
